### ISSUE TITLE
Unhandled exception. System.InvalidOperationException: Unable to find the required services. Please add all the required services by calling 'IServiceCollection.AddAuthorization' in the application startup code

### ISSUE THREAD

**Issue by madeyoga** [madeyoga/AuthEndpoints#56]
```cs
Unhandled exception. System.InvalidOperationException: Unable to find the required services. Please add all the required services by calling 'IServiceCollection.AddAuthorization' in the application startup code.
   at Microsoft.AspNetCore.Builder.AuthorizationAppBuilderExtensions.VerifyServicesRegistered(IApplicationBuilder app)
   at Microsoft.AspNetCore.Builder.AuthorizationAppBuilderExtensions.UseAuthorization(IApplicationBuilder app)
```

Adding `IServiceCollection.AddAuthorization` into `ServiceCollectionExtensions.ConfigureServices` may fix this issue

**Comment by madeyoga** [comment]
#62

**Comment by infobrixGit** [comment]
Hi, the answer is too short. "Adding IServiceCollection.AddAuthorization into ServiceCollectionExtensions.ConfigureServices may fix this issue" where can I find this?
